
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'StoreinoWelcome': typeof import("../components/StoreinoWelcome.vue")['default']
    'AppsLoader': typeof import("../components/apps/loader.vue")['default']
    'BlogArticles': typeof import("../components/blog/Articles.vue")['default']
    'BlogBanner': typeof import("../components/blog/Banner.vue")['default']
    'BlogCategories': typeof import("../components/blog/Categories.vue")['default']
    'BlogNav': typeof import("../components/blog/Nav.vue")['default']
    'BlogPosts': typeof import("../components/blog/Posts.vue")['default']
    'BlogProducts': typeof import("../components/blog/Products.vue")['default']
    'BlogSort': typeof import("../components/blog/Sort.vue")['default']
    'BlogToggle': typeof import("../components/blog/Toggle.vue")['default']
    'CartButtons': typeof import("../components/cart/Buttons.vue")['default']
    'CartEmpty': typeof import("../components/cart/Empty.vue")['default']
    'CartFeatures': typeof import("../components/cart/Features.vue")['default']
    'CartItem': typeof import("../components/cart/Item.vue")['default']
    'CartNav': typeof import("../components/cart/Nav.vue")['default']
    'CartRemoveAll': typeof import("../components/cart/RemoveAll.vue")['default']
    'CartTotals': typeof import("../components/cart/Totals.vue")['default']
    'CollectionsBanner': typeof import("../components/collections/Banner.vue")['default']
    'ElementCollection': typeof import("../components/element/Collection.vue")['default']
    'ElementPost': typeof import("../components/element/Post.vue")['default']
    'ElementProduct': typeof import("../components/element/Product.vue")['default']
    'FooterAbout': typeof import("../components/footer/About.vue")['default']
    'FooterMenu': typeof import("../components/footer/Menu.vue")['default']
    'FooterPayments': typeof import("../components/footer/Payments.vue")['default']
    'FooterPhone': typeof import("../components/footer/Phone.vue")['default']
    'FooterSocialMedia': typeof import("../components/footer/SocialMedia.vue")['default']
    'GlobalButton': typeof import("../components/global/Button.vue")['default']
    'GlobalCopyright': typeof import("../components/global/Copyright.vue")['default']
    'GlobalFooter': typeof import("../components/global/Footer.vue")['default']
    'GlobalMainText': typeof import("../components/global/MainText.vue")['default']
    'GlobalMessageBar': typeof import("../components/global/MessageBar.vue")['default']
    'GlobalNav': typeof import("../components/global/Nav.vue")['default']
    'GlobalSectionHeader': typeof import("../components/global/SectionHeader.vue")['default']
    'GlobalSectionLink': typeof import("../components/global/SectionLink.vue")['default']
    'GlobalSideBar': typeof import("../components/global/SideBar.vue")['default']
    'GlobalTopHeader': typeof import("../components/global/TopHeader.vue")['default']
    'GlobalTopScroll': typeof import("../components/global/TopScroll.vue")['default']
    'GlobalHeader': typeof import("../components/global/header.vue")['default']
    'HeaderIcons': typeof import("../components/header/Icons.vue")['default']
    'HeaderLogo': typeof import("../components/header/Logo.vue")['default']
    'HeaderMenu': typeof import("../components/header/Menu.vue")['default']
    'HeaderSearch': typeof import("../components/header/Search.vue")['default']
    'HomeBanners': typeof import("../components/home/Banners.vue")['default']
    'HomeBrands': typeof import("../components/home/Brands.vue")['default']
    'HomeCollections': typeof import("../components/home/Collections.vue")['default']
    'HomeHero': typeof import("../components/home/Hero.vue")['default']
    'HomeLocation': typeof import("../components/home/Location.vue")['default']
    'HomeOffers': typeof import("../components/home/Offers.vue")['default']
    'HomePosts': typeof import("../components/home/Posts.vue")['default']
    'HomeProducts': typeof import("../components/home/Products.vue")['default']
    'HomeSelections': typeof import("../components/home/Selections.vue")['default']
    'HomeServices': typeof import("../components/home/Services.vue")['default']
    'HomeSlider': typeof import("../components/home/Slider.vue")['default']
    'HomeStyles': typeof import("../components/home/Styles.vue")['default']
    'ImageLoader': typeof import("../components/image/Loader.vue")['default']
    'LoaderAccount': typeof import("../components/loader/Account.vue")['default']
    'LoaderGlobal': typeof import("../components/loader/global.vue")['default']
    'MaintenancePage': typeof import("../components/maintenance/page.vue")['default']
    'MenusCollections': typeof import("../components/menus/Collections.vue")['default']
    'MenusPages': typeof import("../components/menus/Pages.vue")['default']
    'PagesDetails': typeof import("../components/pages/Details.vue")['default']
    'PagesShareButtons': typeof import("../components/pages/ShareButtons.vue")['default']
    'PostContent': typeof import("../components/post/Content.vue")['default']
    'PostDetails': typeof import("../components/post/Details.vue")['default']
    'PostImage': typeof import("../components/post/Image.vue")['default']
    'PostRelated': typeof import("../components/post/Related.vue")['default']
    'PostShareButtons': typeof import("../components/post/ShareButtons.vue")['default']
    'ProductActions': typeof import("../components/product/Actions.vue")['default']
    'ProductContent': typeof import("../components/product/Content.vue")['default']
    'ProductDetails': typeof import("../components/product/Details.vue")['default']
    'ProductImageGallery': typeof import("../components/product/ImageGallery.vue")['default']
    'ProductImageTest': typeof import("../components/product/ImageTest.vue")['default']
    'ProductImagesSlider': typeof import("../components/product/ImagesSlider.vue")['default']
    'ProductPrice': typeof import("../components/product/Price.vue")['default']
    'ProductQuantity': typeof import("../components/product/Quantity.vue")['default']
    'ProductRelated': typeof import("../components/product/Related.vue")['default']
    'ProductReviews': typeof import("../components/product/Reviews.vue")['default']
    'ProductUpsell': typeof import("../components/product/Upsell.vue")['default']
    'ProductVariants': typeof import("../components/product/Variants.vue")['default']
    'ReviewsAvatar': typeof import("../components/reviews/Avatar.vue")['default']
    'SectionsApplication': typeof import("../components/sections/Application.vue")['default']
    'SectionsFetch': typeof import("../components/sections/Fetch.vue")['default']
    'SectionsSettings': typeof import("../components/sections/Settings.vue")['default']
    'ShopArticles': typeof import("../components/shop/Articles.vue")['default']
    'ShopBanner': typeof import("../components/shop/Banner.vue")['default']
    'ShopBrandsFilter': typeof import("../components/shop/BrandsFilter.vue")['default']
    'ShopCollectionsFilter': typeof import("../components/shop/CollectionsFilter.vue")['default']
    'ShopColorsFilter': typeof import("../components/shop/ColorsFilter.vue")['default']
    'ShopGridView': typeof import("../components/shop/GridView.vue")['default']
    'ShopNav': typeof import("../components/shop/Nav.vue")['default']
    'ShopPagination': typeof import("../components/shop/Pagination.vue")['default']
    'ShopPriceFilter': typeof import("../components/shop/PriceFilter.vue")['default']
    'ShopPriceRange': typeof import("../components/shop/PriceRange.vue")['default']
    'ShopProducts': typeof import("../components/shop/Products.vue")['default']
    'ShopSidebarToggle': typeof import("../components/shop/SidebarToggle.vue")['default']
    'ShopSizesFilter': typeof import("../components/shop/SizesFilter.vue")['default']
    'ShopSort': typeof import("../components/shop/Sort.vue")['default']
    'ShopTagsFilter': typeof import("../components/shop/TagsFilter.vue")['default']
    'SiAppLoader': typeof import("../components/si/AppLoader.vue")['default']
    'SidebarCheckbox': typeof import("../components/sidebar/Checkbox.vue")['default']
    'SidebarChild': typeof import("../components/sidebar/Child.vue")['default']
    'WishlistEmpty': typeof import("../components/wishlist/Empty.vue")['default']
    'WishlistNav': typeof import("../components/wishlist/Nav.vue")['default']
    'WishlistProduct': typeof import("../components/wishlist/Product.vue")['default']
    'WishlistRemoveAll': typeof import("../components/wishlist/RemoveAll.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']
    'NuxtPicture': typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']
    'Icon': typeof import("../node_modules/@nuxt/icon/dist/runtime/components/index")['default']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyStoreinoWelcome': typeof import("../components/StoreinoWelcome.vue")['default']
    'LazyAppsLoader': typeof import("../components/apps/loader.vue")['default']
    'LazyBlogArticles': typeof import("../components/blog/Articles.vue")['default']
    'LazyBlogBanner': typeof import("../components/blog/Banner.vue")['default']
    'LazyBlogCategories': typeof import("../components/blog/Categories.vue")['default']
    'LazyBlogNav': typeof import("../components/blog/Nav.vue")['default']
    'LazyBlogPosts': typeof import("../components/blog/Posts.vue")['default']
    'LazyBlogProducts': typeof import("../components/blog/Products.vue")['default']
    'LazyBlogSort': typeof import("../components/blog/Sort.vue")['default']
    'LazyBlogToggle': typeof import("../components/blog/Toggle.vue")['default']
    'LazyCartButtons': typeof import("../components/cart/Buttons.vue")['default']
    'LazyCartEmpty': typeof import("../components/cart/Empty.vue")['default']
    'LazyCartFeatures': typeof import("../components/cart/Features.vue")['default']
    'LazyCartItem': typeof import("../components/cart/Item.vue")['default']
    'LazyCartNav': typeof import("../components/cart/Nav.vue")['default']
    'LazyCartRemoveAll': typeof import("../components/cart/RemoveAll.vue")['default']
    'LazyCartTotals': typeof import("../components/cart/Totals.vue")['default']
    'LazyCollectionsBanner': typeof import("../components/collections/Banner.vue")['default']
    'LazyElementCollection': typeof import("../components/element/Collection.vue")['default']
    'LazyElementPost': typeof import("../components/element/Post.vue")['default']
    'LazyElementProduct': typeof import("../components/element/Product.vue")['default']
    'LazyFooterAbout': typeof import("../components/footer/About.vue")['default']
    'LazyFooterMenu': typeof import("../components/footer/Menu.vue")['default']
    'LazyFooterPayments': typeof import("../components/footer/Payments.vue")['default']
    'LazyFooterPhone': typeof import("../components/footer/Phone.vue")['default']
    'LazyFooterSocialMedia': typeof import("../components/footer/SocialMedia.vue")['default']
    'LazyGlobalButton': typeof import("../components/global/Button.vue")['default']
    'LazyGlobalCopyright': typeof import("../components/global/Copyright.vue")['default']
    'LazyGlobalFooter': typeof import("../components/global/Footer.vue")['default']
    'LazyGlobalMainText': typeof import("../components/global/MainText.vue")['default']
    'LazyGlobalMessageBar': typeof import("../components/global/MessageBar.vue")['default']
    'LazyGlobalNav': typeof import("../components/global/Nav.vue")['default']
    'LazyGlobalSectionHeader': typeof import("../components/global/SectionHeader.vue")['default']
    'LazyGlobalSectionLink': typeof import("../components/global/SectionLink.vue")['default']
    'LazyGlobalSideBar': typeof import("../components/global/SideBar.vue")['default']
    'LazyGlobalTopHeader': typeof import("../components/global/TopHeader.vue")['default']
    'LazyGlobalTopScroll': typeof import("../components/global/TopScroll.vue")['default']
    'LazyGlobalHeader': typeof import("../components/global/header.vue")['default']
    'LazyHeaderIcons': typeof import("../components/header/Icons.vue")['default']
    'LazyHeaderLogo': typeof import("../components/header/Logo.vue")['default']
    'LazyHeaderMenu': typeof import("../components/header/Menu.vue")['default']
    'LazyHeaderSearch': typeof import("../components/header/Search.vue")['default']
    'LazyHomeBanners': typeof import("../components/home/Banners.vue")['default']
    'LazyHomeBrands': typeof import("../components/home/Brands.vue")['default']
    'LazyHomeCollections': typeof import("../components/home/Collections.vue")['default']
    'LazyHomeHero': typeof import("../components/home/Hero.vue")['default']
    'LazyHomeLocation': typeof import("../components/home/Location.vue")['default']
    'LazyHomeOffers': typeof import("../components/home/Offers.vue")['default']
    'LazyHomePosts': typeof import("../components/home/Posts.vue")['default']
    'LazyHomeProducts': typeof import("../components/home/Products.vue")['default']
    'LazyHomeSelections': typeof import("../components/home/Selections.vue")['default']
    'LazyHomeServices': typeof import("../components/home/Services.vue")['default']
    'LazyHomeSlider': typeof import("../components/home/Slider.vue")['default']
    'LazyHomeStyles': typeof import("../components/home/Styles.vue")['default']
    'LazyImageLoader': typeof import("../components/image/Loader.vue")['default']
    'LazyLoaderAccount': typeof import("../components/loader/Account.vue")['default']
    'LazyLoaderGlobal': typeof import("../components/loader/global.vue")['default']
    'LazyMaintenancePage': typeof import("../components/maintenance/page.vue")['default']
    'LazyMenusCollections': typeof import("../components/menus/Collections.vue")['default']
    'LazyMenusPages': typeof import("../components/menus/Pages.vue")['default']
    'LazyPagesDetails': typeof import("../components/pages/Details.vue")['default']
    'LazyPagesShareButtons': typeof import("../components/pages/ShareButtons.vue")['default']
    'LazyPostContent': typeof import("../components/post/Content.vue")['default']
    'LazyPostDetails': typeof import("../components/post/Details.vue")['default']
    'LazyPostImage': typeof import("../components/post/Image.vue")['default']
    'LazyPostRelated': typeof import("../components/post/Related.vue")['default']
    'LazyPostShareButtons': typeof import("../components/post/ShareButtons.vue")['default']
    'LazyProductActions': typeof import("../components/product/Actions.vue")['default']
    'LazyProductContent': typeof import("../components/product/Content.vue")['default']
    'LazyProductDetails': typeof import("../components/product/Details.vue")['default']
    'LazyProductImageGallery': typeof import("../components/product/ImageGallery.vue")['default']
    'LazyProductImageTest': typeof import("../components/product/ImageTest.vue")['default']
    'LazyProductImagesSlider': typeof import("../components/product/ImagesSlider.vue")['default']
    'LazyProductPrice': typeof import("../components/product/Price.vue")['default']
    'LazyProductQuantity': typeof import("../components/product/Quantity.vue")['default']
    'LazyProductRelated': typeof import("../components/product/Related.vue")['default']
    'LazyProductReviews': typeof import("../components/product/Reviews.vue")['default']
    'LazyProductUpsell': typeof import("../components/product/Upsell.vue")['default']
    'LazyProductVariants': typeof import("../components/product/Variants.vue")['default']
    'LazyReviewsAvatar': typeof import("../components/reviews/Avatar.vue")['default']
    'LazySectionsApplication': typeof import("../components/sections/Application.vue")['default']
    'LazySectionsFetch': typeof import("../components/sections/Fetch.vue")['default']
    'LazySectionsSettings': typeof import("../components/sections/Settings.vue")['default']
    'LazyShopArticles': typeof import("../components/shop/Articles.vue")['default']
    'LazyShopBanner': typeof import("../components/shop/Banner.vue")['default']
    'LazyShopBrandsFilter': typeof import("../components/shop/BrandsFilter.vue")['default']
    'LazyShopCollectionsFilter': typeof import("../components/shop/CollectionsFilter.vue")['default']
    'LazyShopColorsFilter': typeof import("../components/shop/ColorsFilter.vue")['default']
    'LazyShopGridView': typeof import("../components/shop/GridView.vue")['default']
    'LazyShopNav': typeof import("../components/shop/Nav.vue")['default']
    'LazyShopPagination': typeof import("../components/shop/Pagination.vue")['default']
    'LazyShopPriceFilter': typeof import("../components/shop/PriceFilter.vue")['default']
    'LazyShopPriceRange': typeof import("../components/shop/PriceRange.vue")['default']
    'LazyShopProducts': typeof import("../components/shop/Products.vue")['default']
    'LazyShopSidebarToggle': typeof import("../components/shop/SidebarToggle.vue")['default']
    'LazyShopSizesFilter': typeof import("../components/shop/SizesFilter.vue")['default']
    'LazyShopSort': typeof import("../components/shop/Sort.vue")['default']
    'LazyShopTagsFilter': typeof import("../components/shop/TagsFilter.vue")['default']
    'LazySiAppLoader': typeof import("../components/si/AppLoader.vue")['default']
    'LazySidebarCheckbox': typeof import("../components/sidebar/Checkbox.vue")['default']
    'LazySidebarChild': typeof import("../components/sidebar/Child.vue")['default']
    'LazyWishlistEmpty': typeof import("../components/wishlist/Empty.vue")['default']
    'LazyWishlistNav': typeof import("../components/wishlist/Nav.vue")['default']
    'LazyWishlistProduct': typeof import("../components/wishlist/Product.vue")['default']
    'LazyWishlistRemoveAll': typeof import("../components/wishlist/RemoveAll.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']
    'LazyNuxtPicture': typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']
    'LazyIcon': typeof import("../node_modules/@nuxt/icon/dist/runtime/components/index")['default']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const StoreinoWelcome: typeof import("../components/StoreinoWelcome.vue")['default']
export const AppsLoader: typeof import("../components/apps/loader.vue")['default']
export const BlogArticles: typeof import("../components/blog/Articles.vue")['default']
export const BlogBanner: typeof import("../components/blog/Banner.vue")['default']
export const BlogCategories: typeof import("../components/blog/Categories.vue")['default']
export const BlogNav: typeof import("../components/blog/Nav.vue")['default']
export const BlogPosts: typeof import("../components/blog/Posts.vue")['default']
export const BlogProducts: typeof import("../components/blog/Products.vue")['default']
export const BlogSort: typeof import("../components/blog/Sort.vue")['default']
export const BlogToggle: typeof import("../components/blog/Toggle.vue")['default']
export const CartButtons: typeof import("../components/cart/Buttons.vue")['default']
export const CartEmpty: typeof import("../components/cart/Empty.vue")['default']
export const CartFeatures: typeof import("../components/cart/Features.vue")['default']
export const CartItem: typeof import("../components/cart/Item.vue")['default']
export const CartNav: typeof import("../components/cart/Nav.vue")['default']
export const CartRemoveAll: typeof import("../components/cart/RemoveAll.vue")['default']
export const CartTotals: typeof import("../components/cart/Totals.vue")['default']
export const CollectionsBanner: typeof import("../components/collections/Banner.vue")['default']
export const ElementCollection: typeof import("../components/element/Collection.vue")['default']
export const ElementPost: typeof import("../components/element/Post.vue")['default']
export const ElementProduct: typeof import("../components/element/Product.vue")['default']
export const FooterAbout: typeof import("../components/footer/About.vue")['default']
export const FooterMenu: typeof import("../components/footer/Menu.vue")['default']
export const FooterPayments: typeof import("../components/footer/Payments.vue")['default']
export const FooterPhone: typeof import("../components/footer/Phone.vue")['default']
export const FooterSocialMedia: typeof import("../components/footer/SocialMedia.vue")['default']
export const GlobalButton: typeof import("../components/global/Button.vue")['default']
export const GlobalCopyright: typeof import("../components/global/Copyright.vue")['default']
export const GlobalFooter: typeof import("../components/global/Footer.vue")['default']
export const GlobalMainText: typeof import("../components/global/MainText.vue")['default']
export const GlobalMessageBar: typeof import("../components/global/MessageBar.vue")['default']
export const GlobalNav: typeof import("../components/global/Nav.vue")['default']
export const GlobalSectionHeader: typeof import("../components/global/SectionHeader.vue")['default']
export const GlobalSectionLink: typeof import("../components/global/SectionLink.vue")['default']
export const GlobalSideBar: typeof import("../components/global/SideBar.vue")['default']
export const GlobalTopHeader: typeof import("../components/global/TopHeader.vue")['default']
export const GlobalTopScroll: typeof import("../components/global/TopScroll.vue")['default']
export const GlobalHeader: typeof import("../components/global/header.vue")['default']
export const HeaderIcons: typeof import("../components/header/Icons.vue")['default']
export const HeaderLogo: typeof import("../components/header/Logo.vue")['default']
export const HeaderMenu: typeof import("../components/header/Menu.vue")['default']
export const HeaderSearch: typeof import("../components/header/Search.vue")['default']
export const HomeBanners: typeof import("../components/home/Banners.vue")['default']
export const HomeBrands: typeof import("../components/home/Brands.vue")['default']
export const HomeCollections: typeof import("../components/home/Collections.vue")['default']
export const HomeHero: typeof import("../components/home/Hero.vue")['default']
export const HomeLocation: typeof import("../components/home/Location.vue")['default']
export const HomeOffers: typeof import("../components/home/Offers.vue")['default']
export const HomePosts: typeof import("../components/home/Posts.vue")['default']
export const HomeProducts: typeof import("../components/home/Products.vue")['default']
export const HomeSelections: typeof import("../components/home/Selections.vue")['default']
export const HomeServices: typeof import("../components/home/Services.vue")['default']
export const HomeSlider: typeof import("../components/home/Slider.vue")['default']
export const HomeStyles: typeof import("../components/home/Styles.vue")['default']
export const ImageLoader: typeof import("../components/image/Loader.vue")['default']
export const LoaderAccount: typeof import("../components/loader/Account.vue")['default']
export const LoaderGlobal: typeof import("../components/loader/global.vue")['default']
export const MaintenancePage: typeof import("../components/maintenance/page.vue")['default']
export const MenusCollections: typeof import("../components/menus/Collections.vue")['default']
export const MenusPages: typeof import("../components/menus/Pages.vue")['default']
export const PagesDetails: typeof import("../components/pages/Details.vue")['default']
export const PagesShareButtons: typeof import("../components/pages/ShareButtons.vue")['default']
export const PostContent: typeof import("../components/post/Content.vue")['default']
export const PostDetails: typeof import("../components/post/Details.vue")['default']
export const PostImage: typeof import("../components/post/Image.vue")['default']
export const PostRelated: typeof import("../components/post/Related.vue")['default']
export const PostShareButtons: typeof import("../components/post/ShareButtons.vue")['default']
export const ProductActions: typeof import("../components/product/Actions.vue")['default']
export const ProductContent: typeof import("../components/product/Content.vue")['default']
export const ProductDetails: typeof import("../components/product/Details.vue")['default']
export const ProductImageGallery: typeof import("../components/product/ImageGallery.vue")['default']
export const ProductImageTest: typeof import("../components/product/ImageTest.vue")['default']
export const ProductImagesSlider: typeof import("../components/product/ImagesSlider.vue")['default']
export const ProductPrice: typeof import("../components/product/Price.vue")['default']
export const ProductQuantity: typeof import("../components/product/Quantity.vue")['default']
export const ProductRelated: typeof import("../components/product/Related.vue")['default']
export const ProductReviews: typeof import("../components/product/Reviews.vue")['default']
export const ProductUpsell: typeof import("../components/product/Upsell.vue")['default']
export const ProductVariants: typeof import("../components/product/Variants.vue")['default']
export const ReviewsAvatar: typeof import("../components/reviews/Avatar.vue")['default']
export const SectionsApplication: typeof import("../components/sections/Application.vue")['default']
export const SectionsFetch: typeof import("../components/sections/Fetch.vue")['default']
export const SectionsSettings: typeof import("../components/sections/Settings.vue")['default']
export const ShopArticles: typeof import("../components/shop/Articles.vue")['default']
export const ShopBanner: typeof import("../components/shop/Banner.vue")['default']
export const ShopBrandsFilter: typeof import("../components/shop/BrandsFilter.vue")['default']
export const ShopCollectionsFilter: typeof import("../components/shop/CollectionsFilter.vue")['default']
export const ShopColorsFilter: typeof import("../components/shop/ColorsFilter.vue")['default']
export const ShopGridView: typeof import("../components/shop/GridView.vue")['default']
export const ShopNav: typeof import("../components/shop/Nav.vue")['default']
export const ShopPagination: typeof import("../components/shop/Pagination.vue")['default']
export const ShopPriceFilter: typeof import("../components/shop/PriceFilter.vue")['default']
export const ShopPriceRange: typeof import("../components/shop/PriceRange.vue")['default']
export const ShopProducts: typeof import("../components/shop/Products.vue")['default']
export const ShopSidebarToggle: typeof import("../components/shop/SidebarToggle.vue")['default']
export const ShopSizesFilter: typeof import("../components/shop/SizesFilter.vue")['default']
export const ShopSort: typeof import("../components/shop/Sort.vue")['default']
export const ShopTagsFilter: typeof import("../components/shop/TagsFilter.vue")['default']
export const SiAppLoader: typeof import("../components/si/AppLoader.vue")['default']
export const SidebarCheckbox: typeof import("../components/sidebar/Checkbox.vue")['default']
export const SidebarChild: typeof import("../components/sidebar/Child.vue")['default']
export const WishlistEmpty: typeof import("../components/wishlist/Empty.vue")['default']
export const WishlistNav: typeof import("../components/wishlist/Nav.vue")['default']
export const WishlistProduct: typeof import("../components/wishlist/Product.vue")['default']
export const WishlistRemoveAll: typeof import("../components/wishlist/RemoveAll.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']
export const NuxtPicture: typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']
export const Icon: typeof import("../node_modules/@nuxt/icon/dist/runtime/components/index")['default']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyStoreinoWelcome: typeof import("../components/StoreinoWelcome.vue")['default']
export const LazyAppsLoader: typeof import("../components/apps/loader.vue")['default']
export const LazyBlogArticles: typeof import("../components/blog/Articles.vue")['default']
export const LazyBlogBanner: typeof import("../components/blog/Banner.vue")['default']
export const LazyBlogCategories: typeof import("../components/blog/Categories.vue")['default']
export const LazyBlogNav: typeof import("../components/blog/Nav.vue")['default']
export const LazyBlogPosts: typeof import("../components/blog/Posts.vue")['default']
export const LazyBlogProducts: typeof import("../components/blog/Products.vue")['default']
export const LazyBlogSort: typeof import("../components/blog/Sort.vue")['default']
export const LazyBlogToggle: typeof import("../components/blog/Toggle.vue")['default']
export const LazyCartButtons: typeof import("../components/cart/Buttons.vue")['default']
export const LazyCartEmpty: typeof import("../components/cart/Empty.vue")['default']
export const LazyCartFeatures: typeof import("../components/cart/Features.vue")['default']
export const LazyCartItem: typeof import("../components/cart/Item.vue")['default']
export const LazyCartNav: typeof import("../components/cart/Nav.vue")['default']
export const LazyCartRemoveAll: typeof import("../components/cart/RemoveAll.vue")['default']
export const LazyCartTotals: typeof import("../components/cart/Totals.vue")['default']
export const LazyCollectionsBanner: typeof import("../components/collections/Banner.vue")['default']
export const LazyElementCollection: typeof import("../components/element/Collection.vue")['default']
export const LazyElementPost: typeof import("../components/element/Post.vue")['default']
export const LazyElementProduct: typeof import("../components/element/Product.vue")['default']
export const LazyFooterAbout: typeof import("../components/footer/About.vue")['default']
export const LazyFooterMenu: typeof import("../components/footer/Menu.vue")['default']
export const LazyFooterPayments: typeof import("../components/footer/Payments.vue")['default']
export const LazyFooterPhone: typeof import("../components/footer/Phone.vue")['default']
export const LazyFooterSocialMedia: typeof import("../components/footer/SocialMedia.vue")['default']
export const LazyGlobalButton: typeof import("../components/global/Button.vue")['default']
export const LazyGlobalCopyright: typeof import("../components/global/Copyright.vue")['default']
export const LazyGlobalFooter: typeof import("../components/global/Footer.vue")['default']
export const LazyGlobalMainText: typeof import("../components/global/MainText.vue")['default']
export const LazyGlobalMessageBar: typeof import("../components/global/MessageBar.vue")['default']
export const LazyGlobalNav: typeof import("../components/global/Nav.vue")['default']
export const LazyGlobalSectionHeader: typeof import("../components/global/SectionHeader.vue")['default']
export const LazyGlobalSectionLink: typeof import("../components/global/SectionLink.vue")['default']
export const LazyGlobalSideBar: typeof import("../components/global/SideBar.vue")['default']
export const LazyGlobalTopHeader: typeof import("../components/global/TopHeader.vue")['default']
export const LazyGlobalTopScroll: typeof import("../components/global/TopScroll.vue")['default']
export const LazyGlobalHeader: typeof import("../components/global/header.vue")['default']
export const LazyHeaderIcons: typeof import("../components/header/Icons.vue")['default']
export const LazyHeaderLogo: typeof import("../components/header/Logo.vue")['default']
export const LazyHeaderMenu: typeof import("../components/header/Menu.vue")['default']
export const LazyHeaderSearch: typeof import("../components/header/Search.vue")['default']
export const LazyHomeBanners: typeof import("../components/home/Banners.vue")['default']
export const LazyHomeBrands: typeof import("../components/home/Brands.vue")['default']
export const LazyHomeCollections: typeof import("../components/home/Collections.vue")['default']
export const LazyHomeHero: typeof import("../components/home/Hero.vue")['default']
export const LazyHomeLocation: typeof import("../components/home/Location.vue")['default']
export const LazyHomeOffers: typeof import("../components/home/Offers.vue")['default']
export const LazyHomePosts: typeof import("../components/home/Posts.vue")['default']
export const LazyHomeProducts: typeof import("../components/home/Products.vue")['default']
export const LazyHomeSelections: typeof import("../components/home/Selections.vue")['default']
export const LazyHomeServices: typeof import("../components/home/Services.vue")['default']
export const LazyHomeSlider: typeof import("../components/home/Slider.vue")['default']
export const LazyHomeStyles: typeof import("../components/home/Styles.vue")['default']
export const LazyImageLoader: typeof import("../components/image/Loader.vue")['default']
export const LazyLoaderAccount: typeof import("../components/loader/Account.vue")['default']
export const LazyLoaderGlobal: typeof import("../components/loader/global.vue")['default']
export const LazyMaintenancePage: typeof import("../components/maintenance/page.vue")['default']
export const LazyMenusCollections: typeof import("../components/menus/Collections.vue")['default']
export const LazyMenusPages: typeof import("../components/menus/Pages.vue")['default']
export const LazyPagesDetails: typeof import("../components/pages/Details.vue")['default']
export const LazyPagesShareButtons: typeof import("../components/pages/ShareButtons.vue")['default']
export const LazyPostContent: typeof import("../components/post/Content.vue")['default']
export const LazyPostDetails: typeof import("../components/post/Details.vue")['default']
export const LazyPostImage: typeof import("../components/post/Image.vue")['default']
export const LazyPostRelated: typeof import("../components/post/Related.vue")['default']
export const LazyPostShareButtons: typeof import("../components/post/ShareButtons.vue")['default']
export const LazyProductActions: typeof import("../components/product/Actions.vue")['default']
export const LazyProductContent: typeof import("../components/product/Content.vue")['default']
export const LazyProductDetails: typeof import("../components/product/Details.vue")['default']
export const LazyProductImageGallery: typeof import("../components/product/ImageGallery.vue")['default']
export const LazyProductImageTest: typeof import("../components/product/ImageTest.vue")['default']
export const LazyProductImagesSlider: typeof import("../components/product/ImagesSlider.vue")['default']
export const LazyProductPrice: typeof import("../components/product/Price.vue")['default']
export const LazyProductQuantity: typeof import("../components/product/Quantity.vue")['default']
export const LazyProductRelated: typeof import("../components/product/Related.vue")['default']
export const LazyProductReviews: typeof import("../components/product/Reviews.vue")['default']
export const LazyProductUpsell: typeof import("../components/product/Upsell.vue")['default']
export const LazyProductVariants: typeof import("../components/product/Variants.vue")['default']
export const LazyReviewsAvatar: typeof import("../components/reviews/Avatar.vue")['default']
export const LazySectionsApplication: typeof import("../components/sections/Application.vue")['default']
export const LazySectionsFetch: typeof import("../components/sections/Fetch.vue")['default']
export const LazySectionsSettings: typeof import("../components/sections/Settings.vue")['default']
export const LazyShopArticles: typeof import("../components/shop/Articles.vue")['default']
export const LazyShopBanner: typeof import("../components/shop/Banner.vue")['default']
export const LazyShopBrandsFilter: typeof import("../components/shop/BrandsFilter.vue")['default']
export const LazyShopCollectionsFilter: typeof import("../components/shop/CollectionsFilter.vue")['default']
export const LazyShopColorsFilter: typeof import("../components/shop/ColorsFilter.vue")['default']
export const LazyShopGridView: typeof import("../components/shop/GridView.vue")['default']
export const LazyShopNav: typeof import("../components/shop/Nav.vue")['default']
export const LazyShopPagination: typeof import("../components/shop/Pagination.vue")['default']
export const LazyShopPriceFilter: typeof import("../components/shop/PriceFilter.vue")['default']
export const LazyShopPriceRange: typeof import("../components/shop/PriceRange.vue")['default']
export const LazyShopProducts: typeof import("../components/shop/Products.vue")['default']
export const LazyShopSidebarToggle: typeof import("../components/shop/SidebarToggle.vue")['default']
export const LazyShopSizesFilter: typeof import("../components/shop/SizesFilter.vue")['default']
export const LazyShopSort: typeof import("../components/shop/Sort.vue")['default']
export const LazyShopTagsFilter: typeof import("../components/shop/TagsFilter.vue")['default']
export const LazySiAppLoader: typeof import("../components/si/AppLoader.vue")['default']
export const LazySidebarCheckbox: typeof import("../components/sidebar/Checkbox.vue")['default']
export const LazySidebarChild: typeof import("../components/sidebar/Child.vue")['default']
export const LazyWishlistEmpty: typeof import("../components/wishlist/Empty.vue")['default']
export const LazyWishlistNav: typeof import("../components/wishlist/Nav.vue")['default']
export const LazyWishlistProduct: typeof import("../components/wishlist/Product.vue")['default']
export const LazyWishlistRemoveAll: typeof import("../components/wishlist/RemoveAll.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']
export const LazyNuxtPicture: typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']
export const LazyIcon: typeof import("../node_modules/@nuxt/icon/dist/runtime/components/index")['default']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
